import { motion } from 'framer-motion';

const proofTypes = [
  {
    title: 'Inclusion proof',
    desc: 'Transaction is registered. Eternal validity. Prevents double-spend.',
  },
  {
    title: 'Exclusion proof',
    desc: 'Transaction not yet registered. Valid at moment of generation. Enables low-latency settlement.',
  },
  {
    title: 'Unicity proof',
    desc: 'SMT itself has not forked. Generated by consensus, relayed by Oracle.',
  },
];

const benchmark = [
  { stack: 'Hash-based (no ZK)', speed: '10,000*', proof: '10 MB', asymp: 'O(n)', trusted: 'No', highlight: false, dim: true },
  { stack: 'Gnark + Groth16', speed: '30', proof: '250 b', asymp: 'O(1)', trusted: 'Yes', highlight: false, dim: false },
  { stack: 'AIR + Plonky3', label: '(selected)', speed: '30,000', proof: '1.7 MB', asymp: 'O(log n)', trusted: 'No', highlight: true, dim: false },
  { stack: 'SP1 zkVM', speed: '1.5', proof: '2 MB', asymp: 'O(log n)', trusted: 'No', highlight: false, dim: true },
];

function RoundsDiagram() {
  const W = 480;
  const H = 220;
  const blockW = 90;
  const blockH = 24;
  const gap = 14;
  const startX = 30;
  const blockY = 30;
  const roundY = 90;
  const roundH = 50;
  const font = "'Geist Mono', monospace";

  const rounds = [0, 1, 2, 3];

  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="w-full h-auto">
      {/* Top label */}
      <text x={startX} y={18} fill="rgba(254,254,254,0.55)" fontSize="9" fontFamily={font}
        letterSpacing="1.5">CONSENSUS LAYER (PoW + BFT)</text>

      {/* Block boxes */}
      {rounds.map((_r, i) => {
        const x = startX + i * (blockW + gap);
        return (
          <g key={`block-${i}`}>
            <rect x={x} y={blockY} width={blockW} height={blockH} rx={4}
              fill="rgba(255,255,255,0.04)" stroke="rgba(255,255,255,0.2)" strokeWidth={0.8} />
            <text x={x + blockW / 2} y={blockY + 16} textAnchor="middle"
              fill="rgba(254,254,254,0.85)" fontSize="9" fontFamily={font}>
              block n{i === 0 ? '' : `+${i}`}
            </text>
          </g>
        );
      })}

      {/* Down arrows + ZK proof labels */}
      {rounds.map((_r, i) => {
        const x = startX + i * (blockW + gap) + blockW / 2;
        return (
          <g key={`down-${i}`}>
            <line x1={x} y1={blockY + blockH + 1} x2={x} y2={roundY - 1}
              stroke="rgba(249,115,22,0.45)" strokeWidth={1} strokeDasharray="2 2" />
            <text x={x} y={blockY + blockH + 16} textAnchor="middle"
              fill="rgba(249,115,22,0.9)" fontSize="8" fontFamily={font}>ZK proof</text>
          </g>
        );
      })}

      {/* Round boxes (SMT) */}
      {rounds.map((r, i) => {
        const x = startX + i * (blockW + gap);
        return (
          <g key={`round-${i}`}>
            <rect x={x} y={roundY} width={blockW} height={roundH} rx={6}
              fill="rgba(249,115,22,0.06)" stroke="rgba(249,115,22,0.55)" strokeWidth={1} />
            <text x={x + blockW / 2} y={roundY + 16} textAnchor="middle"
              fill="#fefefe" fontSize="11" fontWeight="bold" fontFamily="Anton, sans-serif"
              letterSpacing="0.5">
              ROUND {r}
            </text>
            <text x={x + blockW / 2} y={roundY + 30} textAnchor="middle"
              fill="rgba(254,254,254,0.7)" fontSize="9" fontFamily={font}>SMT</text>
            <text x={x + blockW / 2} y={roundY + 43} textAnchor="middle"
              fill="rgba(249,115,22,0.85)" fontSize="9" fontFamily={font}>root r{r}</text>
          </g>
        );
      })}

      {/* Time arrow on the right */}
      <text x={W - 22} y={roundY + 32} fill="rgba(254,254,254,0.5)" fontSize="9" fontFamily={font}>time →</text>

      {/* Down arrows from rounds + requests/proofs label */}
      {rounds.map((_r, i) => {
        const x = startX + i * (blockW + gap) + blockW / 2;
        return (
          <g key={`bot-${i}`}>
            <line x1={x} y1={roundY + roundH + 1} x2={x} y2={roundY + roundH + 22}
              stroke="rgba(255,255,255,0.18)" strokeWidth={0.8} strokeDasharray="2 2" />
            <text x={x} y={roundY + roundH + 36} textAnchor="middle"
              fill="rgba(254,254,254,0.5)" fontSize="8" fontFamily={font}>requests + proofs</text>
          </g>
        );
      })}
    </svg>
  );
}

export function ZKOracleSlide() {
  return (
    <div className="fixed inset-0 z-50 bg-[#060606] overflow-hidden">
      <div className="relative z-10 h-full flex flex-col px-6 sm:px-10 lg:px-16 py-6 sm:py-8 lg:py-10 justify-center gap-4">

        {/* Header */}
        <div className="shrink-0">
          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            className="text-orange-400 text-[10px] sm:text-xs tracking-[0.4em] uppercase"
            style={{ fontFamily: "'Geist Mono', monospace" }}>
            Appendix — Blockchain
          </motion.p>
          <motion.h1 initial={{ opacity: 0, x: -40 }} animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7 }}
            className="text-[#fefefe] text-[24px] sm:text-[34px] lg:text-[44px] leading-[1.05] tracking-tight mt-1"
            style={{ fontFamily: "'Anton', sans-serif" }}>
            THE CORE INNOVATION: <span className="text-orange-400">ZK UNIQUENESS ORACLE</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }}
            className="mt-2 text-[#fefefe]/85 text-xs sm:text-sm lg:text-base max-w-5xl leading-relaxed"
            style={{ fontFamily: "'Geist Mono', monospace" }}>
            Sparse Merkle Tree updated in rounds. State transitions are recorded as leaves. ZK proofs compress consistency to constant size, enabling unlimited horizontal scaling.
          </motion.p>
        </div>

        {/* Two-column body */}
        <div className="grid grid-cols-2 gap-6 lg:gap-10 shrink-0">

          {/* Left — Round-based mechanism */}
          <div className="flex flex-col">
            <p className="text-orange-400 text-[10px] sm:text-xs tracking-[0.3em] uppercase font-bold mb-2"
              style={{ fontFamily: "'Geist Mono', monospace" }}>
              Round-Based Mechanism
            </p>
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.5 }}
              className="rounded-lg p-3 lg:p-4"
              style={{
                border: '1px solid rgba(255,255,255,0.08)',
                background: 'rgba(255,255,255,0.025)',
              }}>
              <RoundsDiagram />
              <p className="text-[#fefefe]/75 text-[11px] sm:text-xs leading-relaxed mt-3"
                style={{ fontFamily: "'Geist Mono', monospace" }}>
                Each round: state transition requests batch into the SMT, root recalculated, ZK consistency proof generated, anchored to consensus. Validators verify the proof and commit. Only requests against the new root are accepted in the next round.
              </p>
            </motion.div>
          </div>

          {/* Right — Three proof types */}
          <div className="flex flex-col">
            <p className="text-orange-400 text-[10px] sm:text-xs tracking-[0.3em] uppercase font-bold mb-2"
              style={{ fontFamily: "'Geist Mono', monospace" }}>
              Three Proof Types
            </p>
            <div className="flex flex-col gap-2">
              {proofTypes.map((p, i) => (
                <motion.div
                  key={p.title}
                  initial={{ opacity: 0, x: 8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.5 + i * 0.1, duration: 0.4 }}
                  className="rounded-lg p-3 lg:p-3.5"
                  style={{
                    border: '1px solid rgba(255,255,255,0.08)',
                    background: 'rgba(255,255,255,0.025)',
                  }}
                >
                  <p className="text-[#fefefe] text-sm sm:text-base font-bold"
                    style={{ fontFamily: "'Geist Mono', monospace" }}>
                    {p.title}
                  </p>
                  <p className="text-[#fefefe]/65 text-[11px] sm:text-xs leading-relaxed mt-1"
                    style={{ fontFamily: "'Geist Mono', monospace" }}>
                    {p.desc}
                  </p>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* Bottom — Benchmark table */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9, duration: 0.5 }}
          className="shrink-0 pt-3 border-t border-white/[0.08]"
        >
          <p className="text-orange-400 text-[10px] sm:text-xs tracking-[0.3em] uppercase font-bold mb-2"
            style={{ fontFamily: "'Geist Mono', monospace" }}>
            ZK Stack Benchmark
          </p>
          <table className="w-full" style={{ fontFamily: "'Geist Mono', monospace" }}>
            <thead>
              <tr className="border-b border-white/[0.1]">
                <th className="text-left py-2 text-[#fefefe]/50 text-[10px] sm:text-xs tracking-[0.18em] uppercase font-normal w-[32%]">
                  Stack
                </th>
                <th className="text-right py-2 text-[#fefefe]/50 text-[10px] sm:text-xs tracking-[0.18em] uppercase font-normal">
                  Per Shard tx/s
                </th>
                <th className="text-right py-2 text-[#fefefe]/50 text-[10px] sm:text-xs tracking-[0.18em] uppercase font-normal">
                  Proof Size
                </th>
                <th className="text-right py-2 text-[#fefefe]/50 text-[10px] sm:text-xs tracking-[0.18em] uppercase font-normal">
                  Asymptotics
                </th>
                <th className="text-right py-2 text-[#fefefe]/50 text-[10px] sm:text-xs tracking-[0.18em] uppercase font-normal">
                  Trusted Setup
                </th>
              </tr>
            </thead>
            <tbody>
              {benchmark.map((b, i) => {
                const baseColor = b.highlight
                  ? 'text-orange-400'
                  : b.dim
                    ? 'text-[#fefefe]/55'
                    : 'text-[#fefefe]/85';
                return (
                  <motion.tr
                    key={b.stack}
                    initial={{ opacity: 0, x: -8 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 1.0 + i * 0.05, duration: 0.3 }}
                    className={i < benchmark.length - 1 ? 'border-b border-white/[0.05]' : ''}
                  >
                    <td className={`py-1.5 text-xs sm:text-sm ${baseColor} ${b.highlight ? 'font-bold' : ''}`}>
                      {b.stack}
                      {b.label && <span className="text-orange-400/80"> {b.label}</span>}
                    </td>
                    <td className={`py-1.5 text-right text-xs sm:text-sm ${baseColor}`}>
                      {b.highlight ? (
                        <span className="px-1.5 py-0.5 rounded text-[#fefefe] font-bold"
                          style={{ background: 'rgba(255,255,255,0.08)' }}>
                          {b.speed}
                        </span>
                      ) : b.speed}
                    </td>
                    <td className={`py-1.5 text-right text-xs sm:text-sm ${baseColor}`}>{b.proof}</td>
                    <td className={`py-1.5 text-right text-xs sm:text-sm ${baseColor}`}>{b.asymp}</td>
                    <td className={`py-1.5 text-right text-xs sm:text-sm ${baseColor}`}>{b.trusted}</td>
                  </motion.tr>
                );
              })}
            </tbody>
          </table>
          <p className="text-[#fefefe]/45 text-[10px] sm:text-xs italic mt-2"
            style={{ fontFamily: "'Geist Mono', monospace" }}>
            30,000 tx/s per shard. Hierarchical sharding enables practically unlimited horizontal scale. Full benchmark in whitepaper Section 4.
          </p>
        </motion.div>

      </div>
    </div>
  );
}
